language: node_js
node_js:
  - "0.12"
  - "0.10"

before_script:
  - npm install -g grunt-cli

script: "npm test && grunt ci"

notifications:
  webhooks:
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
